### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by onlyjob** [SeanDolphin/bqschema#6]
Please consider assigning version numbers and tagging releases. Tags/releases
are useful for downstream package maintainers (in [Debian](http://debian.org) and other distributions) to export source tarballs, automatically track new releases and to declare dependencies between packages. Read more in the [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

Versioning provides additional benefits to encourage vendoring of a particular (e.g. latest stable) release contrary to random unreleased snapshots.

Thank you.

See also
- http://semver.org/
- https://en.wikipedia.org/wiki/Software_versioning

**Comment by SeanDolphin** [comment]
Actually kind of surprised, I had not done any tagged releases on this repo.  I normally do that so I can use gopkg.in and other tools.

**Comment by SeanDolphin** [comment]
If the above release does not meet your needs please comment and I will gladly review the changes required.

**Comment by onlyjob** [comment]
Excellent, thank you very much. :)
